### ISSUE TITLE
CentOS focuses on CentOS Stream

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluent-package-builder#235]
https://blog.centos.org/2020/12/future-is-centos-stream/

This issue is not urgent.

CentOS changes their development plan for CentOS Stream.
We need to consider how to support CentOS Stream and how to support rpm for RHEL versions in the future.

**Comment by cosmo0920** [comment]
FYI: CentOS 8 can migrate CentOS 8 Stream with the following commands:

```
root@centos-linux# dnf install centos-release-stream

root@centos-linux# dnf swap centos-{linux,stream}-repos

root@centos-linux# dnf distro-sync

root@centos-stream# cat /etc/centos-release
CentOS Stream release 8
```

ref: https://centos.org/distro-faq/#q7-how-do-i-migrate-my-centos-linux-8-installation-to-centos-stream

**Comment by kenhys** [comment]
I'm not sure yet, but How about using UBI(Red Hat Universal Base Image)?
I mean that just using it to build with td-agent package.
It resolve to compatibility issue for RHEL.
https://catalog.redhat.com/software/containers/search?q=ubi8&p=1

ref. https://speakerdeck.com/moriwaka/ubi-faq

**Comment by kenhys** [comment]
If CentOS stream keeps compatibility with RHEL at some extent, it may be ok only provide built  with CentOS stream.

**Comment by kenhys** [comment]
We use rocky as a build image for RHEL. See #354
