### ISSUE TITLE
Rebranding td-agent-builder

### ISSUE THREAD

**Issue by kenhys** [fluent/fluent-package-builder#311]
Before moving to fluent organization, rebranding should be done to make it clear that it is the official community-based distribution.
https://github.com/fluent-plugins-nursery/td-agent-builder/issues/277

Currently, there are two distribution are documented - td-agent and calyptia-fluentd.
It may be confused for new users.

Instead of `td-agent`, we should use `fluent-agent` or something

* [x] Rename GitHub repository to ~~fluent-agent-builder~~ fluent-package-builder
  * No side effects
* [x] Replace `td-agent-builder` with `fluent-package-builder` in the documents & code
* [x] Fix embedded path `td-agent` in anywhere for ~~fluent-agent-builder~~ fluent-package-builder
  * Need to work on branch for a while (make it switchable?)
* [x] Support package migration from td-agent to fluent-agent (deb or rpm package dependency fix)
* [ ] T.B.D. use https://td-agent-package-browser.herokuapp.com/ ? 
* [ ] T.B.D. Fix installation script e.g https://toolbelt.treasuredata.com/sh/install-redhat-td-agent4.sh (when it is ready)

**Comment by kou** [comment]
How about `fluentd` not `fluent-agent`?

**Comment by kenhys** [comment]
> How about fluentd not fluent-agent?

:+1: for fluentd.

**Comment by ashie** [comment]
>     * [ ]  Rename GitHub repository to fluent-agent-builder
>       
>       * No side effects

We already experienced organization transfer:
https://github.com/clear-code/td-agent-builder ->
https://github.com/fluent-plugins-nursery/td-agent-builder

I confirmed that renamed project is also redirected to new one:
https://github.com/ashie/test ->
https://github.com/ashie/test-repository-rename

**Comment by ashie** [comment]
>  Rename GitHub repository to fluent-agent-builder

I prefer fluent-package-builder.

**Comment by ashie** [comment]
I'll rename this repository after releasing 4.2.0

**Comment by ashie** [comment]
> I'll rename this repository after releasing 4.2.0

Done.

**Comment by ashie** [comment]
I've post a discussion article about this to [Fluentd's forum](https://github.com/fluent/fluentd/discussions):
[New Release Cycle for td-agent(Fluentd LTS)](https://github.com/fluent/fluentd/discussions/3860).

**Comment by ashie** [comment]
>     * [ ]  T.B.D. use https://td-agent-package-browser.herokuapp.com/ ?

We are asking CNCF whether they can prepare it or not.
Cloudflare is the most likely candidate.

**Comment by kenhys** [comment]
fluent-package v5.0.1 has been released. (officially publish announcement blog articles later)

(Installation script is also updated for fluent-package)

We still use repository hosting on AWS s3 and cloudflare CDN for a while, this TODO: should be treated in another issue.
