### ISSUE TITLE
Remove TD_AGENT_OPTIONS to be defined only once

### ISSUE THREAD

**Issue by kuroponzu** [fluent/fluent-package-builder#352]
When I install td-agent in the below environment and run `sytemctl start td-agent.service`, TD_AGENT_OPTIONS is defined twice.

``` shell
$ cat /lib/systemd/system/td-agent.service
[Unit]
Description=td-agent: Fluentd based data collector for Treasure Data
Documentation=https://docs.treasuredata.com/display/public/PD/About+Treasure+Data%%27s+Server-Side+Agent
After=network-online.target
Wants=network-online.target

[Service]
User=td-agent
Group=td-agent
LimitNOFILE=65536
Environment=LD_PRELOAD=/opt/td-agent/lib/libjemalloc.so
Environment=GEM_HOME=/opt/td-agent/lib/ruby/gems/2.7.0/
Environment=GEM_PATH=/opt/td-agent/lib/ruby/gems/2.7.0/
Environment=FLUENT_CONF=/etc/td-agent/td-agent.conf
Environment=FLUENT_PLUGIN=/etc/td-agent/plugin
Environment=FLUENT_SOCKET=/var/run/td-agent/td-agent.sock
Environment=TD_AGENT_LOG_FILE=/var/log/td-agent/td-agent.log
# First defined!
Environment=TD_AGENT_OPTIONS=
# Second defined in this file!
EnvironmentFile=-/etc/default/td-agent
PIDFile=/var/run/td-agent/td-agent.pid
RuntimeDirectory=td-agent
Type=forking
ExecStart=/opt/td-agent/bin/fluentd --log $TD_AGENT_LOG_FILE --daemon /var/run/td-agent/td-agent.pid $TD_AGENT_OPTIONS
ExecStop=/bin/kill -TERM ${MAINPID}
ExecReload=/bin/kill -HUP ${MAINPID}
Restart=always
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
```

https://github.com/fluent-plugins-nursery/fluent-package-builder/blob/1b2699c15ca018ced6fcfc9c85c77832f6b68149/td-agent/templates/etc/systemd/td-agent.service.erb#L18-L22

``` shell
$ cat /etc/default/td-agent
# Second defined!!
TD_AGENT_OPTIONS=""
```

https://github.com/fluent-plugins-nursery/fluent-package-builder/blob/a419360908e788c6ef1b0ad86f5892fc9dc6866c/td-agent/templates/package-scripts/td-agent/deb/postinst#L47-L54

I don't think it is necessary to define TD_AGENT_OPTIONS twice right after installation.
I assigned a value to TD_AGENT_OPTIONS at `/lib/systemd/system/td-agent.service`, but it was overwritten by `/etc/default/td-agent`. I was very confused by this specification.
So, why don't you remove one of TD_AGENT_OPTIONS?

[environment]
- OS: ubuntu(16.04.7 LTS)
- td-agent(4.3.0)

**Comment by ashie** [comment]
Good catch!
Probably `TD_AGENT_OPTIONS` in td-agent.service should be removed.
In addition, /etc/default/td-agent should be provided as a package file, should not generated by postinst script.
