### ISSUE TITLE
What distro should be support ? (After CentOS 8 EOL)

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-package-builder#354]
Related issue:
* https://github.com/fluent-plugins-nursery/fluent-package-builder/issues/235

CentOS8 is EOLed already.

* Rocky? Stream?

**Comment by kenhys** [comment]
* Rocky seems to be popular by downloads (docker images)
* We just use it build environment, 
* Major cloud providers(AWS, GCP, Azure) supports it

Using RockeyLinux is enough for it.

**Comment by kenhys** [comment]
https://github.com/fluent/fluent-package-builder/pull/357 Rocky is good for it.

**Comment by fujimotos** [comment]
@kenhys Thank you!
