### ISSUE TITLE
Upgrade to fluentd v1.14.4

### ISSUE THREAD

**Issue by roicostas** [fluent/fluent-package-builder#368]
We are seeing two big problems with current version of td-agent due to big lines ( > 1MB, we have seen 130MB lines ... no comments  ) :
- It starts consuming memory until it is killed by OOM ( we have limited it with 1GB of memory which is enough )
- When there are too many logs, and we do have them, it falls behind log generation and keeps references to old files which end up filling up disk space so a manual intervention is required to stop td-agent and remove thoose files.

Currently we have a custom filter that drops big lines but it is still not enough to fix this problems. We have tried fluentd v1.14.4 on development with max_line_size limited to 1024000 bytes and these problems seem to be fixed.

So we are wondering if we can get td-agent updated to v1.14.4.

**Comment by ashie** [comment]
Updated to fluentd v1.14.6 at td-agent v4.3.1.
