### ISSUE TITLE
Manage "Releases"

### ISSUE THREAD

**Issue by ksandrmatveyev** [fluent/fluent-package-builder#372]
Hello,

It would be good to have up-to-date "Releases" page https://github.com/fluent/fluent-package-builder/releases. So, users can subscribe on RSS/Atom feed for new releases only. Instruction https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository. I'd expect something like https://github.com/fluent/fluentd/releases + https://github.com/fluent/fluent-package-builder/blob/master/CHANGELOG.md

Workaround:
Subscribe to tags https://github.com/fluent/fluent-package-builder/tags.atom

**Comment by ashie** [comment]
We started to use GitHub Release since [v4.3.1](https://github.com/fluent/fluent-package-builder/releases/tag/v4.3.1).
