### ISSUE TITLE
Support RHEL9

### ISSUE THREAD

**Issue by ashie** [fluent/fluent-package-builder#388]

**Comment by ashie** [comment]
[Announcing the GA release of Red Hat Enterprise Linux 9.0 ](https://access.redhat.com/announcements/6958409)

**Comment by cosmo0920** [comment]
Perhaps, we can use [ubi9 image](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?container-tabs=overview) to build td-agent package for RHEL 9.

**Comment by hrw** [comment]
quay.io/centos/centos:stream9 exists for quite a while.

**Comment by cosmo0920** [comment]
For supporting RHEL, using ubi image is better instead of quay.io's ones.

**Comment by cosmo0920** [comment]
td-agent had not been released for CentOS Stream: https://td-agent-package-browser.herokuapp.com/4/redhat
Just for released CentOS 7 and 8 and will be 9.

**Comment by ashie** [comment]
We are working on it at #396 (FYI using CentOS Strem 9 isn't our final decision, we'll try other choices).
