### ISSUE TITLE
Did you move apt repository?

### ISSUE THREAD

**Issue by pyama86** [fluent/fluent-package-builder#392]
I have got bellow message.

```
E: Repository 'http://packages.treasuredata.com/4/ubuntu/focal focal InRelease' changed its 'Origin' value from 'focal focal' to 'ubuntu/focal focal'
[15](https://xxx/images/runs/1273975?check_suite_focus=true#step:5:15)
E: Repository 'http://packages.treasuredata.com/4/ubuntu/focal focal InRelease' changed its 'Label' value from 'focal focal' to 'ubuntu/focal focal'
```
have you moved apt repository?

from: http://packages.treasuredata.com
to: https://td-agent-package-browser.herokuapp.com

And then,stil keeped define former in https://toolbelt.treasuredata.com/sh/install-ubuntu-focal-td-agent4.sh

could you check this?

**Comment by ashie** [comment]
Did you run this?: https://docs.fluentd.org/installation/install-by-deb#step-1-install-from-apt-repository

```
$ curl -fsSL https://toolbelt.treasuredata.com/sh/install-ubuntu-focal-td-agent4.sh | sh
```

I don't get such error, installation is succeeded.

**Comment by ashie** [comment]
@kenhys Do you know what it is?

**Comment by kenhys** [comment]
Hmm, as the focal repository was updated recently, maybe it only happens when upgrading.
If so, it is not intended.

NOTE: repository is not changed at all, (I guess) only repository metadata may be upgraded in an unexpected way.

**Comment by kenhys** [comment]
I'll check it.

**Comment by pyama86** [comment]
thanks,I can check and run command if you want.

**Comment by kenhys** [comment]
It seems that it was derived from incompatible aptly publish usage.

**Comment by pyama86** [comment]
Thanks for your quick fix!
