### ISSUE TITLE
'fluent-bit' package for Ubuntu 22.04 in Apt repository

### ISSUE THREAD

**Issue by alexpilon666** [fluent/fluent-package-builder#404]
Hi all,

In the process of upgrading all our servers from Centos 7 to Ubuntu 22.04 and noticed that according to my understanding of [this PR](https://github.com/fluent/fluent-package-builder/pull/381/commits/a6ed37c034c5ce11ef0f9f92d6c658554ef04377), the package should exist in https://packages.fluentbit.io, it doesn't seem to work.

I'm following the instructions [here](https://docs.fluentbit.io/manual/installation/linux/ubuntu), and when adding the repository I'm adding it as `deb [signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/ubuntu/jammy jammy main`, this is what I receive when running an `apt update` : 

> root@f73bd97b4d32:/# apt update
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:3 https://packages.fluentbit.io/ubuntu/jammy jammy InRelease
Err:4 https://packages.fluentbit.io/ubuntu/jammy jammy Release
  404  Not Found [IP: 139.178.85.103 443]
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Reading package lists... Done
E: The repository 'https://packages.fluentbit.io/ubuntu/jammy jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Am I missing something, is it currently in the works, etc. ?

Thanks in advance!

**Comment by ashie** [comment]
This build system supports only Fluentd, not for Fluent Bit.
