### ISSUE TITLE
"SSL_read: unexpected eof while reading" in Ubuntu 22.04/openssl 3.0.2

### ISSUE THREAD

**Issue by drbugfinder-work** [fluent/fluent-package-builder#406]
Hi, 

with the switch from Ubuntu 20.04 to Ubuntu 22.04 (which includes the transition from openssl 1.1.1f to openssl 3.0.2), we are getting the following error message every few seconds with a Forward input (from Fluent Bit) with TLS/SSL encryption:
```
│ 2022-07-25 09:09:34 +0000 [warn]: #0 close socket due to unexpected ssl error: SSL_read: unexpected eof while reading
│ 2022-07-25 09:09:42 +0000 [warn]: #0 close socket due to unexpected ssl error: SSL_read: unexpected eof while reading
```
Maybe it is related to https://github.com/curl/curl/issues/5138 (https://github.com/curl/curl/issues/5138#issuecomment-929945830) 

We cannot see any impact on message handling from Fluent Bit to td-agent. Setting TLS version (of td-agent) did not change the SSL EOF warnings.

We tried with td-agent 4.3.2 and the pre-release version of 4.4.0 and got the same warning.

**Comment by drbugfinder-work** [comment]
To me it looks like td-agent was not updated to use OpenSSL 3, like described here: https://github.com/openssl/openssl/commit/0cd2ee64bffcdece599c3e4b5fac3830a55dc0fa#diff-9a86c74704f3d66bc69ba9cf9dc3168eea957103bcc36f1c2e3a1f05b10188a1R166

**Comment by ashie** [comment]
I close the duplicate issue, let's continue at https://github.com/fluent/fluentd/issues/3833
