### ISSUE TITLE
Remaining issues to support Ruby 3.2

### ISSUE THREAD

**Issue by ashie** [fluent/fluent-package-builder#429]
Although importing Ruby 3.2 has been landed at #425, some gems are still needed to work due to missing `File.exists?` which has been removed as of Ruby 3.2. AFAIK following 3 gems should be fixed.

* [x] https://github.com/fluent/fluent-plugin-opensearch/pull/93
  * Fixed in fluent-pluigin-opensearch 1.0.10
* [x] https://github.com/uken/fluent-plugin-elasticsearch/pull/998
* [x] https://github.com/treasure-data/td/pull/259

**Comment by renan-airbnb** [comment]
Just wanted to chime in and say this is a blocker for packaging on Amazon Linux 2023. Unlike Amazon Linux 2022, AL2023 does not have the `ruby3.1` package 😞.

**Comment by ashie** [comment]
> Just wanted to chime in and say this is a blocker for packaging on Amazon Linux 2023. Unlike Amazon Linux 2022, AL2023 does not have the `ruby3.1` package [used to build in AL2022](https://github.com/fluent/fluent-package-builder/blob/master/td-agent/yum/amazonlinux-2022/Dockerfile#L47-L49) disappointed.

Don't worry, it's still there and buildable: #435

**Comment by ashie** [comment]
Oh I didn't notice it. Thanks for notifying it!
The ruby version for building td-agent isn't so tight, so it's no problem to use 3.2 too.
But it seems that we should fix the Dockerfile to avoid confusing.
