### ISSUE TITLE
Merge style

### ISSUE THREAD

**Issue by kou** [fluent/fluent-package-builder#431]
How about using only squash merge and changing the default merge message to "Default to pull request title and description"?

 In general, one pull request has one logical change. So squashing commits in a pull request will not loss useful information.  And a merge commit will be meaningless.
 
 In general, each pull request has meaningful title and description. So they will be suitable commit title and message too.

**Comment by daipom** [comment]
I agree!

**Comment by kou** [comment]
@ashie What do you think about this?

**Comment by ashie** [comment]
Basically I agree with you.
The remaining concern is that how to conform to DCO style.
Since this project is Fluentd's sub project I think this project should follow the DCO style.

**Comment by kou** [comment]
All trailers including`Signed-off-by` are kept with "Default to pull request title and description".
So we can keep the DCO style with this change.

**Comment by ashie** [comment]
I see, thanks.
I've changed the repository setting.
