### ISSUE TITLE
td-agent Install script for Amazon Linux 2023

### ISSUE THREAD

**Issue by shiino-shunsuke** [fluent/fluent-package-builder#441]
### Is your feature request related to a problem? Please describe.

I tried to install td-agent 3 on amazon linux 2023 but could not because the install script does not exist.
https://docs.treasuredata.com/display/public/PD/Installing+td-agent+on+AWS+Linux

### Describe the solution you'd like

Could you please provide an installation script for amazon linux 2023?

### Describe alternatives you've considered

No alternative was found.
If you have a workaround, please let us know.

**Comment by ashie** [comment]
td-agent 3 never support Amazon Linux 2023, it's already EOL.
For td-agent 4 or later, we are developing it but not released officially yet.

**Comment by SupermanAdam007** [comment]
Hi, please any update on this? Thank you.

**Comment by kenhys** [comment]
Amazon Linux 2023 will not be supported in td-agent v4.
Instead fluent-package supports it (fluent-package is successor of td-agent v4)

See https://docs.fluentd.org/installation/install-by-rpm#amazon-linux

**Comment by SupermanAdam007** [comment]
@kenhys Amazing, thank you! I spend yesterday to build the package https://github.com/SupermanAdam007/fluent-packages/tree/main, but I am happy that it is officially supported. :)
