### ISSUE TITLE
Is it possible/supported to change the install directory?

### ISSUE THREAD

**Issue by Jakub-Kapusta** [fluent/fluent-package-builder#488]
I am wondering if changing the install directory is doable?

The systems I am working with use a custom directory to install everything, and I would like to install the td-agent in that specific directory.

**Comment by ashie** [comment]
For Windows, it's possible.
For other systems, it's not possible and hard to support.
It depends on the package systems of each systems.

**Comment by Jakub-Kapusta** [comment]
Thank you for your response.
> For other systems, it's not possible and hard to support.

I am mostly concerned with CentOS, so I understand that I need to work with the current defaul directory.
