### ISSUE TITLE
Dependency tree broken for Ubuntu 22.04

### ISSUE THREAD

**Issue by sagarsaini1** [fluent/fluent-package-builder#563]
### Is your feature request related to a problem? Please describe.

dependency tree is broken for ubuntu 22.04; unable to install

### Describe the solution you'd like

this broken dependency issue to be resolved.

### Describe alternatives you've considered

tried solving the issue with installing the dependency libraries manually but that didn't work.

### Additional context

this is the error I'm facing: 
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 td-agent : Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by kenhys** [comment]
At least, it can't be reproducible on ubuntu 22.04.


```
$ apt show td-agent
Package: td-agent
Version: 4.5.0-1
Priority: optional
Section: net
Maintainer: Fluentd developers <fluentd@googlegroups.com>
Installed-Size: 72.2 MB
Pre-Depends: adduser
Depends: libc6 (>= 2.35), libcrypt1 (>= 1:4.1.0), libgmp10 (>= 2:6.2.1+dfsg), libssl3 (>= 3.0.0~~alpha1), libyaml-0-2, zlib1g (>= 1:1.2.2)
Homepage: https://www.fluentd.org/
Download-Size: 11.9 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.treasuredata.com/4/ubuntu/jammy jammy/contrib amd64 Packages
Description: Treasure Agent: A data collector for Treasure Data
 Treasure Agent is all in one package which contains Fluentd and
 related gem packages.
 .
 It is installable alongside with system's gem packages separately.

```

**Comment by sagarsaini1** [comment]
Hi @kenhys @ashie , I have followed the above mentioned steps but it is still not getting installed getting the below errors:
This error is coming in the latest installer 4.5.0-1 : 
`apt install -y ./td-agent_4.5.0-1_arm64\ \(1\).deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'td-agent:arm64' instead of './td-agent_4.5.0-1_arm64 (1).deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 td-agent:arm64 : Depends: libc6:arm64 (>= 2.35) but it is not installable
                  Depends: libcrypt1:arm64 (>= 1:4.1.0) but it is not installable
                  Depends: libgmp10:arm64 (>= 2:6.2.1+dfsg) but it is not installable
                  Depends: libssl3:arm64 (>= 3.0.0~~alpha1) but it is not installable
                  Depends: libyaml-0-2:arm64 but it is not installable
                  Depends: zlib1g:arm64 (>= 1:1.2.2) but it is not installable
E: Unable to correct problems, you have held broken packages.`


Getting below error with the script present in the official documentation:
`Selecting previously unselected package gnupg-utils.
Preparing to unpack .../06-gnupg-utils_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gnupg-utils (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpg.
Preparing to unpack .../07-gpg_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package pinentry-curses.
Preparing to unpack .../08-pinentry-curses_1.1.1-1build2_amd64.deb ...
Unpacking pinentry-curses (1.1.1-1build2) ...
Selecting previously unselected package gpg-agent.
Preparing to unpack .../09-gpg-agent_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg-agent (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpg-wks-client.
Preparing to unpack .../10-gpg-wks-client_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg-wks-client (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpg-wks-server.
Preparing to unpack .../11-gpg-wks-server_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg-wks-server (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpgsm.
Preparing to unpack .../12-gpgsm_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpgsm (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gnupg.
Preparing to unpack .../13-gnupg_2.2.27-3ubuntu2.1_all.deb ...
Unpacking gnupg (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package fluentd-apt-source.
Preparing to unpack .../14-td-agent-apt-source.deb ...
Unpacking fluentd-apt-source (2020.8.25-1) ...
Setting up libksba8:amd64 (1.6.0-2ubuntu0.2) ...
Setting up libnpth0:amd64 (1.6-3build2) ...
Setting up libassuan0:amd64 (2.5.5-1build1) ...
Setting up gnupg-l10n (2.2.27-3ubuntu2.1) ...
Setting up gpgconf (2.2.27-3ubuntu2.1) ...
Setting up gpg (2.2.27-3ubuntu2.1) ...
Setting up gnupg-utils (2.2.27-3ubuntu2.1) ...
Setting up pinentry-curses (1.1.1-1build2) ...
Setting up gpg-agent (2.2.27-3ubuntu2.1) ...
Usage: systemctl [options] command [name...]

systemctl: error: no such option: --global
/usr/bin/deb-systemd-helper: error: systemctl preset failed on gpg-agent-browser.socket: No such file or directory
Usage: systemctl [options] command [name...]

systemctl: error: no such option: --global
/usr/bin/deb-systemd-helper: error: systemctl preset failed on gpg-agent-extra.socket: No such file or directory
Usage: systemctl [options] command [name...]

systemctl: error: no such option: --global
/usr/bin/deb-systemd-helper: error: systemctl preset failed on gpg-agent-ssh.socket: No such file or directory
Usage: systemctl [options] command [name...]

systemctl: error: no such option: --global
/usr/bin/deb-systemd-helper: error: systemctl preset failed on gpg-agent.socket: No such file or directory
Setting up gpgsm (2.2.27-3ubuntu2.1) ...
Setting up dirmngr (2.2.27-3ubuntu2.1) ...
Usage: systemctl [options] command [name...]

systemctl: error: no such option: --global
/usr/bin/deb-systemd-helper: error: systemctl preset failed on dirmngr.socket: No such file or directory
Setting up gpg-wks-server (2.2.27-3ubuntu2.1) ...
Setting up gpg-wks-client (2.2.27-3ubuntu2.1) ...
Setting up gnupg (2.2.27-3ubuntu2.1) ...
Setting up fluentd-apt-source (2020.8.25-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [833 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1235 kB]
Get:7 https://packages.treasuredata.com/4/ubuntu/jammy jammy InRelease [7686 B]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [979 kB]
Get:9 https://packages.treasuredata.com/4/ubuntu/jammy jammy/contrib amd64 Packages [1909 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [864 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1104 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [25.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [49.2 kB]
Fetched 5438 kB in 5s (1133 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libyaml-0-2
The following NEW packages will be installed:
  libyaml-0-2 td-agent
0 upgraded, 2 newly installed, 0 to remove and 8 not upgraded.
Need to get 11.9 MB of archives.
After this operation, 72.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libyaml-0-2 amd64 0.2.2-1build2 [51.6 kB]
Get:2 https://packages.treasuredata.com/4/ubuntu/jammy jammy/contrib amd64 td-agent amd64 4.5.0-1 [11.9 MB]
Fetched 11.9 MB in 3s (3769 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libyaml-0-2:amd64.
(Reading database ... 8178 files and directories currently installed.)
Preparing to unpack .../libyaml-0-2_0.2.2-1build2_amd64.deb ...
Unpacking libyaml-0-2:amd64 (0.2.2-1build2) ........................................................................]
Selecting previously unselected package td-agent....................................................................]
Preparing to unpack .../td-agent_4.5.0-1_amd64.deb ...
Unpacking td-agent (4.5.0-1) ...##################..................................................................]
Setting up libyaml-0-2:amd64 (0.2.2-1build2) ...#############.......................................................]
Setting up td-agent (4.5.0-1) ...##################################################.................................]
debconf: unable to initialize frontend: Dialog################################################......................]
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Adding system user `td-agent' (UID 101) ...
Adding new group `td-agent' (GID 101) ...
Adding new user `td-agent' (UID 101) with group `td-agent' ...
Creating home directory `/var/lib/td-agent' ...
/usr/bin/deb-systemd-helper: error: systemctl preset failed on td-agent.service: No such file or directory
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...###################################################...........]`




Note: I'm trying to install td-agent on a docker image of ubuntu 22.04 but I think it should be fine!

**Comment by kenhys** [comment]
> Note: I'm trying to install td-agent on a docker image of ubuntu 22.04 but I think it should be fine!

td-agent is not designed to be installed  for docker image.

**Comment by kenhys** [comment]
And more, usually amd64.deb and arm64.deb should not be mixed.

```
Hi @kenhys @ashie , I have followed the above mentioned steps but it is still not getting installed getting the below errors:
This error is coming in the latest installer 4.5.0-1 :
`apt install -y ./td-agent_4.5.0-1_arm64\ (1).deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'td-agent:arm64' instead of './td-agent_4.5.0-1_arm64 (1).deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
td-agent:arm64 : Depends: libc6:arm64 (>= 2.35) but it is not installable
Depends: libcrypt1:arm64 (>= 1:4.1.0) but it is not installable
Depends: libgmp10:arm64 (>= 2:6.2.1+dfsg) but it is not installable
Depends: libssl3:arm64 (>= 3.0.0~~alpha1) but it is not installable
Depends: libyaml-0-2:arm64 but it is not installable
Depends: zlib1g:arm64 (>= 1:1.2.2) but it is not installable
E: Unable to correct problems, you have held broken packages.`

Getting below error with the script present in the official documentation:
`Selecting previously unselected package gnupg-utils.
Preparing to unpack .../06-gnupg-utils_2.2.27-3ubuntu2.1_amd64.deb ...
```
