### ISSUE TITLE
bundle newer fluent-diagtool which suppors fluent-package 

### ISSUE THREAD

**Issue by kenhys** [fluent/fluent-package-builder#571]
# Problem

fluent-diagtool 1.0.1 doesn't support fluent-package even though HEAD.

it affects collecting gem list and service information.

# Expected

support fluent-package in fluent-diagtool and bundle released a new version for fluent-package.

# Additional information

https://github.com/fluent/diagtool/pull/12 will resolve such a situation.

https://github.com/fluent/diagtool/pull/9, https://github.com/fluent/diagtool/pull/10, https://github.com/fluent/diagtool/pull/11 also fixes minor issues.

**Comment by kenhys** [comment]
As PR is not merged and not shipped yet, it was not bundled to v5.0.1 .

**Comment by kubotat** [comment]
@kenhys I uploaded the latest fluent-diagtool v1.0.2 on rubygem.com which supports `fluent-package`. Just for your information.

**Comment by kenhys** [comment]
@kubotat Thanks!!

**Comment by kenhys** [comment]
TODO: close this issue when bundling PR is merged.

**Comment by kenhys** [comment]
#578 will solve it.
