### ISSUE TITLE
Use ruby 3.2.3

### ISSUE THREAD

**Issue by kenhys** [fluent/fluent-package-builder#612]
Upgrade bundled ruby from 3.2.2 to 3.2.3

There are some backported fixes such as:

[Bug #20096: Ruby 3.2.2 win32/registry: Junk appended to Windows Registry String Value](https://bugs.ruby-lang.org/issues/20096)

**Comment by daipom** [comment]
Note: That bug of Ruby 3.2.2 influences `--reg-winsvc-fluentdopt`.
Garbage data can be included at the end of `fluentdopt`.
The possible damage to Fluentd is not yet certain.

**Comment by daipom** [comment]
> Note: That bug of Ruby 3.2.2 influences `--reg-winsvc-fluentdopt`. Garbage data can be included at the end of `fluentdopt`. The possible damage to Fluentd is not yet certain.

* #619

It will be fixed by using Ruby 3.2.3.
There is NO problem with Fluentd's behavior, so it seems less urgent.

**Comment by ashie** [comment]
Fixed via #626
