### ISSUE TITLE
Windows: a garbage character is sometimes placed at the end of 'fluentdopt' registry value (fluent-package)

### ISSUE THREAD

**Issue by daipom** [fluent/fluent-package-builder#619]
# Abst

* A garbage character is sometimes placed at the end of `fluentdopt` registry value
* There is NO problem with Fluentd's behavior
  * The terminating character at the end can be incorrect
  * However, it does not impact the Fluentd's behavior since [Ruby chops the character regardless of the content](https://github.com/ruby/ruby/blob/v3_2_2/ext/win32/lib/win32/registry.rb#L652)
* This is the bug of Ruby, and it has been fixed since Ruby 3.2.3
  * https://bugs.ruby-lang.org/issues/20096
  * https://github.com/ruby/ruby/commit/051a874325c177e040301878069c2b28f5d06ce6
  * It reproduces on Ruby 3.2.2 only, but that bug of Ruby exists from at least Ruby 2 series
  * I don't understand why it reproduces on Ruby 3.2.2 only (fluent-package v5.0.0 ~ v5.0.2)

# Details

I feel like 100 characters would be easy to reproduce.
(I am not sure if the number of characters really has anything to do with the ease of reproduction.)

```cmd
> fluentd --reg-winsvc-fluentdopt aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

![2024-02-16_12h09_16](https://github.com/fluent/fluent-package-builder/assets/12229857/def685a1-8353-4db8-a27d-9488169362fb)

Confirm the value:

```rb
 require "win32/registry"
 
 Win32::Registry::HKEY_LOCAL_MACHINE.open("SYSTEM\\CurrentControlSet\\Services\\fluentdwinsvc") do |reg|
   p reg.read("fluentdopt")[1] # A
   type, data = Win32::Registry::API.QueryValue(reg.hkey, "fluentdopt")
   p data.encode(Encoding::UTF_8, Encoding::UTF_16LE) # B
   p data.encode(Encoding::UTF_8, Encoding::UTF_16LE).bytes #C
 end
```

A:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

B:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaꘀ"

C:[97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 234, 152, 128]

The garbage character can be different.

**Comment by ashie** [comment]
We confirmed that it's completely harmless because:

>       * However, it does not impact the Fluentd's behavior since [Ruby chops the character regardless of the content](https://github.com/ruby/ruby/blob/v3_2_2/ext/win32/lib/win32/registry.rb#L652)

We suspected it might be the cause of #618, but we've confirmed that it's not applicable too.
So we no longer need to track this issue.

**Comment by daipom** [comment]
Agreed.
It will be fixed when updating the Ruby.
We don't need to track this issue.
