### ISSUE TITLE
Install win32-service gem from a forked repository

### ISSUE THREAD

**Issue by ashie** [fluent/fluent-package-builder#630]
Until https://github.com/chef/win32-service/pull/85 is merged, we need to install our forked win32-service gem to fix #618 because it's a critical issue on certain environment.
We have already a feature to install fluentd gem from GitHub & local repository.
It would be nice if we add a feature to be able to do it also other gem.
@kenhys Could you take a look this?

@daipom Could you move https://github.com/daipom/win32-service to https://github.com/fluent-plugins-nursery? We need to maintain it by our team, not a person.

**Comment by daipom** [comment]
> @daipom Could you move https://github.com/daipom/win32-service to https://github.com/fluent-plugins-nursery? We need to maintain it by our team, not a person.

Sure! I agree!

**Comment by daipom** [comment]
> > @daipom Could you move https://github.com/daipom/win32-service to https://github.com/fluent-plugins-nursery? We need to maintain it by our team, not a person.
> 
> Sure! I agree!

Transferred to https://github.com/fluent-plugins-nursery/win32-service.
